### ISSUE TITLE
SignIn page, SingUp page

### ISSUE THREAD

**Issue by danielzordan** [danielzordan/gobarber-mobile#2]
# SignIn
![image](https://user-images.githubusercontent.com/20348582/93125365-086cd200-f699-11ea-8a8f-5a1081d91ca0.png)

# SignUp
![image](https://user-images.githubusercontent.com/20348582/93125405-1589c100-f699-11ea-8fa4-448f7ababa31.png)

**Comment by Zordanppp** [comment]
![image](https://user-images.githubusercontent.com/20348582/93125506-3e11bb00-f699-11ea-8c10-3e20e3ab4273.png)
